# Generated by Django 5.0.6 on 2024-08-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_about_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
