# Generated by Django 5.0.7 on 2024-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_portfoliocategory_delete_portfolioitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Images/portfolio_single')),
            ],
        ),
    ]
