# Generated by Django 5.0.7 on 2024-08-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_gallery_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
