# Generated by Django 5.0.7 on 2024-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_created_date_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
