# Generated by Django 5.0.7 on 2024-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_single',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
