# Generated by Django 5.0.7 on 2024-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_gallery_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery_Single',
        ),
    ]
